// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: dialogs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DialogServiceClient is the client API for DialogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DialogServiceClient interface {
	Send(ctx context.Context, in *DialogSendRequest, opts ...grpc.CallOption) (*DialogSendResponse, error)
	List(ctx context.Context, in *DialogListRequest, opts ...grpc.CallOption) (*DialogListResponse, error)
	SendWithoutToken(ctx context.Context, in *DialogSendWTRequest, opts ...grpc.CallOption) (*DialogSendResponse, error)
	ListWithoutToken(ctx context.Context, in *DialogListWTRequest, opts ...grpc.CallOption) (*DialogListResponse, error)
}

type dialogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogServiceClient(cc grpc.ClientConnInterface) DialogServiceClient {
	return &dialogServiceClient{cc}
}

func (c *dialogServiceClient) Send(ctx context.Context, in *DialogSendRequest, opts ...grpc.CallOption) (*DialogSendResponse, error) {
	out := new(DialogSendResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) List(ctx context.Context, in *DialogListRequest, opts ...grpc.CallOption) (*DialogListResponse, error) {
	out := new(DialogListResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) SendWithoutToken(ctx context.Context, in *DialogSendWTRequest, opts ...grpc.CallOption) (*DialogSendResponse, error) {
	out := new(DialogSendResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/SendWithoutToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) ListWithoutToken(ctx context.Context, in *DialogListWTRequest, opts ...grpc.CallOption) (*DialogListResponse, error) {
	out := new(DialogListResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/ListWithoutToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DialogServiceServer is the server API for DialogService service.
// All implementations must embed UnimplementedDialogServiceServer
// for forward compatibility
type DialogServiceServer interface {
	Send(context.Context, *DialogSendRequest) (*DialogSendResponse, error)
	List(context.Context, *DialogListRequest) (*DialogListResponse, error)
	SendWithoutToken(context.Context, *DialogSendWTRequest) (*DialogSendResponse, error)
	ListWithoutToken(context.Context, *DialogListWTRequest) (*DialogListResponse, error)
	mustEmbedUnimplementedDialogServiceServer()
}

// UnimplementedDialogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDialogServiceServer struct {
}

func (UnimplementedDialogServiceServer) Send(context.Context, *DialogSendRequest) (*DialogSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedDialogServiceServer) List(context.Context, *DialogListRequest) (*DialogListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDialogServiceServer) SendWithoutToken(context.Context, *DialogSendWTRequest) (*DialogSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWithoutToken not implemented")
}
func (UnimplementedDialogServiceServer) ListWithoutToken(context.Context, *DialogListWTRequest) (*DialogListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithoutToken not implemented")
}
func (UnimplementedDialogServiceServer) mustEmbedUnimplementedDialogServiceServer() {}

// UnsafeDialogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DialogServiceServer will
// result in compilation errors.
type UnsafeDialogServiceServer interface {
	mustEmbedUnimplementedDialogServiceServer()
}

func RegisterDialogServiceServer(s grpc.ServiceRegistrar, srv DialogServiceServer) {
	s.RegisterService(&DialogService_ServiceDesc, srv)
}

func _DialogService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).Send(ctx, req.(*DialogSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).List(ctx, req.(*DialogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_SendWithoutToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogSendWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).SendWithoutToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/SendWithoutToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).SendWithoutToken(ctx, req.(*DialogSendWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_ListWithoutToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogListWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).ListWithoutToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/ListWithoutToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).ListWithoutToken(ctx, req.(*DialogListWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DialogService_ServiceDesc is the grpc.ServiceDesc for DialogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DialogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DialogService",
	HandlerType: (*DialogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _DialogService_Send_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DialogService_List_Handler,
		},
		{
			MethodName: "SendWithoutToken",
			Handler:    _DialogService_SendWithoutToken_Handler,
		},
		{
			MethodName: "ListWithoutToken",
			Handler:    _DialogService_ListWithoutToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialogs.proto",
}
