// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dialogs.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialogSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	From   string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DialogSendRequest) Reset() {
	*x = DialogSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogSendRequest) ProtoMessage() {}

func (x *DialogSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogSendRequest.ProtoReflect.Descriptor instead.
func (*DialogSendRequest) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{0}
}

func (x *DialogSendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DialogSendRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DialogSendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DialogSendWTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserFrom string `protobuf:"bytes,1,opt,name=user_from,json=userFrom,proto3" json:"user_from,omitempty"`
	UserTo   string `protobuf:"bytes,2,opt,name=user_to,json=userTo,proto3" json:"user_to,omitempty"`
	Text     string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DialogSendWTRequest) Reset() {
	*x = DialogSendWTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogSendWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogSendWTRequest) ProtoMessage() {}

func (x *DialogSendWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogSendWTRequest.ProtoReflect.Descriptor instead.
func (*DialogSendWTRequest) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{1}
}

func (x *DialogSendWTRequest) GetUserFrom() string {
	if x != nil {
		return x.UserFrom
	}
	return ""
}

func (x *DialogSendWTRequest) GetUserTo() string {
	if x != nil {
		return x.UserTo
	}
	return ""
}

func (x *DialogSendWTRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DialogSendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DialogSendResponse) Reset() {
	*x = DialogSendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogSendResponse) ProtoMessage() {}

func (x *DialogSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogSendResponse.ProtoReflect.Descriptor instead.
func (*DialogSendResponse) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{2}
}

func (x *DialogSendResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DialogSendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DialogListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	From   string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *DialogListRequest) Reset() {
	*x = DialogListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogListRequest) ProtoMessage() {}

func (x *DialogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogListRequest.ProtoReflect.Descriptor instead.
func (*DialogListRequest) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{3}
}

func (x *DialogListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DialogListRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type DialogListWTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserFrom string `protobuf:"bytes,1,opt,name=user_from,json=userFrom,proto3" json:"user_from,omitempty"`
	UserTo   string `protobuf:"bytes,2,opt,name=user_to,json=userTo,proto3" json:"user_to,omitempty"`
}

func (x *DialogListWTRequest) Reset() {
	*x = DialogListWTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogListWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogListWTRequest) ProtoMessage() {}

func (x *DialogListWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogListWTRequest.ProtoReflect.Descriptor instead.
func (*DialogListWTRequest) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{4}
}

func (x *DialogListWTRequest) GetUserFrom() string {
	if x != nil {
		return x.UserFrom
	}
	return ""
}

func (x *DialogListWTRequest) GetUserTo() string {
	if x != nil {
		return x.UserTo
	}
	return ""
}

type DialogListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   uint32           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message  string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Messages []*DialogMessage `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *DialogListResponse) Reset() {
	*x = DialogListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogListResponse) ProtoMessage() {}

func (x *DialogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogListResponse.ProtoReflect.Descriptor instead.
func (*DialogListResponse) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{5}
}

func (x *DialogListResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DialogListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DialogListResponse) GetMessages() []*DialogMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DialogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DialogMessage) Reset() {
	*x = DialogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogMessage) ProtoMessage() {}

func (x *DialogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dialogs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogMessage.ProtoReflect.Descriptor instead.
func (*DialogMessage) Descriptor() ([]byte, []int) {
	return file_dialogs_proto_rawDescGZIP(), []int{6}
}

func (x *DialogMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DialogMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DialogMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_dialogs_proto protoreflect.FileDescriptor

var file_dialogs_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x11, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x5f, 0x0a, 0x13, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x46, 0x0a, 0x12, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x11, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x4b, 0x0a, 0x13, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x57, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x54, 0x6f, 0x22, 0x78, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x0d,
	0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0xbd, 0x03, 0x0a, 0x0d, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x64,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x2f,
	0x73, 0x65, 0x6e, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x5b, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x64,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x2f,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x78, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68,
	0x6f, 0x75, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x54, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x22, 0x22, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x7d, 0x2f, 0x7b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x74, 0x6f, 0x7d, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x75,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x24, 0x12, 0x22, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x7d, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x7d,
	0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dialogs_proto_rawDescOnce sync.Once
	file_dialogs_proto_rawDescData = file_dialogs_proto_rawDesc
)

func file_dialogs_proto_rawDescGZIP() []byte {
	file_dialogs_proto_rawDescOnce.Do(func() {
		file_dialogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_dialogs_proto_rawDescData)
	})
	return file_dialogs_proto_rawDescData
}

var file_dialogs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dialogs_proto_goTypes = []interface{}{
	(*DialogSendRequest)(nil),   // 0: proto.DialogSendRequest
	(*DialogSendWTRequest)(nil), // 1: proto.DialogSendWTRequest
	(*DialogSendResponse)(nil),  // 2: proto.DialogSendResponse
	(*DialogListRequest)(nil),   // 3: proto.DialogListRequest
	(*DialogListWTRequest)(nil), // 4: proto.DialogListWTRequest
	(*DialogListResponse)(nil),  // 5: proto.DialogListResponse
	(*DialogMessage)(nil),       // 6: proto.DialogMessage
}
var file_dialogs_proto_depIdxs = []int32{
	6, // 0: proto.DialogListResponse.messages:type_name -> proto.DialogMessage
	0, // 1: proto.DialogService.Send:input_type -> proto.DialogSendRequest
	3, // 2: proto.DialogService.List:input_type -> proto.DialogListRequest
	1, // 3: proto.DialogService.SendWithoutToken:input_type -> proto.DialogSendWTRequest
	4, // 4: proto.DialogService.ListWithoutToken:input_type -> proto.DialogListWTRequest
	2, // 5: proto.DialogService.Send:output_type -> proto.DialogSendResponse
	5, // 6: proto.DialogService.List:output_type -> proto.DialogListResponse
	2, // 7: proto.DialogService.SendWithoutToken:output_type -> proto.DialogSendResponse
	5, // 8: proto.DialogService.ListWithoutToken:output_type -> proto.DialogListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dialogs_proto_init() }
func file_dialogs_proto_init() {
	if File_dialogs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dialogs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogSendWTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogSendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogListWTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dialogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dialogs_proto_goTypes,
		DependencyIndexes: file_dialogs_proto_depIdxs,
		MessageInfos:      file_dialogs_proto_msgTypes,
	}.Build()
	File_dialogs_proto = out.File
	file_dialogs_proto_rawDesc = nil
	file_dialogs_proto_goTypes = nil
	file_dialogs_proto_depIdxs = nil
}
