env: "local"
storage_path: "host=localhost port=15432 user=postgres password=example dbname=otus_homework sslmode=disable"
storage_path_for_read: "host=localhost port=5432 user=postgres password=example dbname=otus_homework sslmode=disable"
cache_path: "redis://localhost:6379/1"
rqueue_path: "amqp://guest:guest@localhost:5672/"
grpc:  
  port: 9001  
  web_port: 8087
  ws_port:  8088
  timeout: 10h
