env: "local"
storage_path: "host=haproxy-lb port=5000 user=postgres password=example dbname=otus_homework sslmode=disable"
storage_path_for_read: "host=haproxy-lb port=5001 user=postgres password=example dbname=otus_homework sslmode=disable"
cache_path: "redis://cache_master:6379/1"
rqueue_path: "amqp://guest:guest@rabbit:5672/"
grpc:  
  port: 9001  
  web_port: 8087
  ws_port:  8088
  timeout: 10h
app:
  name: "app-1"
  id: 1