env: "local"
# postgres:
# storage_path: "host=citus_master port=5432 user=postgres password=example dbname=postgres sslmode=disable"
# tarantool:
storage_path: "tara:3301"
grpc:  
  port: 9002  
  web_port: 9087
  ws_port:  9088
  timeout: 10h
auth_path: "http://nginx:80/auth/get"
